=== JulietteBenguigui/TEI_XML_French-Breton_dict/dtd.dtd
<?xml encoding="UTF-8"?>

<!-- TEI HEADER -->
<!ELEMENT TEI (teiHeader, text)>
<!ATTLIST TEI xmlns CDATA #IMPLIED>

<!ELEMENT teiHeader (fileDesc, encodingDesc?, profileDesc?)>

<!ELEMENT fileDesc (titleStmt, editionStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT editionStmt (edition, respStmt) >
<!ELEMENT edition (#PCDATA) >
<!ELEMENT respStmt (resp, name) >
<!ELEMENT resp (#PCDATA) >
<!ELEMENT name (#PCDATA) >

<!ELEMENT publicationStmt (distributor?, date?, availability)>
<!ELEMENT distributor (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT availability (licence)>
<!ELEMENT licence (ref?)>
<!ELEMENT ref (#PCDATA)>

<!ELEMENT sourceDesc (p)>
<!ELEMENT p (#PCDATA)>

<!ELEMENT encodingDesc (projectDesc, samplingDecl) >
<!ELEMENT projectDesc (p) >
<!ELEMENT samplingDecl (p) >

<!ELEMENT profileDesc (langUsage?, textDesc?)>
<!ELEMENT langUsage (language)>
<!ELEMENT language (#PCDATA)>
<!ATTLIST language ident CDATA #IMPLIED>

<!ELEMENT textDesc (channel?, constitution?, derivation?, domain?, factuality?, interaction?, preparedness?, purpose?)>
<!ATTLIST textDesc n CDATA #IMPLIED>
<!ELEMENT channel (#PCDATA)>
<!ELEMENT constitution (#PCDATA)>
<!ELEMENT derivation (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT factuality (#PCDATA)>
<!ELEMENT interaction (#PCDATA)>
<!ELEMENT preparedness (#PCDATA)>
<!ELEMENT purpose (#PCDATA)>

<!ELEMENT text (body)>
<!ELEMENT body (head?, div)>
<!ELEMENT head (#PCDATA)>

<!ELEMENT div (head?, pb?, fw?, entry*)>
<!ELEMENT pb EMPTY>
<!ELEMENT fw (#PCDATA)>

<!ELEMENT entry (form, sense?, cit*)>
<!ELEMENT form (orth, gramGrp?)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT gramGrp (gen?, pos?, number?)>
<!ELEMENT gen (#PCDATA)>
<!ELEMENT pos (#PCDATA)>
<!ELEMENT number (#PCDATA)>

<!ELEMENT sense (#PCDATA)>

<!ELEMENT cit (quote, cit?)>
<!ATTLIST cit type (translation | example) #REQUIRED
                    xml:lang CDATA #IMPLIED>
<!ELEMENT quote (#PCDATA)>

=== JulietteBenguigui/TEI_XML_French-Breton_dict/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "dtd.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
     <fileDesc>
        <titleStmt>
           <title></title>
        </titleStmt>
        <editionStmt>
           <edition></edition>
           <respStmt>
              <resp></resp>
              <name></name>
           </respStmt>
        </editionStmt>
        <publicationStmt>
           <distributor></distributor>
           <date></date>
           <availability>
              <licence>
                 <ref/>
              </licence>
           </availability>
        </publicationStmt>
        <sourceDesc>
            <p></p>
        </sourceDesc>
     </fileDesc>
     
     <encodingDesc>
        <projectDesc>
           <p></p>
        </projectDesc>
        <samplingDecl>
           <p></p>
        </samplingDecl>
     </encodingDesc>
     
     <!-- VERIFIER TOUT CA -->
     <profileDesc> 
        <langUsage>
           <language ident=""></language>
        </langUsage>
        <textDesc n="">
           <channel></channel>
           <constitution/>
           <derivation/>
           <domain/>
           <factuality></factuality>
           <interaction></interaction>
           <preparedness></preparedness>
           <purpose></purpose>
        </textDesc>
     </profileDesc>
 
  </teiHeader>
  
   
   <text>
      <body>
         <head></head>
         <div>
            <head></head>
            <pb/>
            <fw></fw>
            <entry>
               <form>
                  <orth></orth>
                  <gramGrp>
                     <gen></gen>
                     <pos></pos>
                     <number></number>
                  </gramGrp>
               </form>
               <sense></sense>
               <cit type="translation" xml:lang="en">
                  <quote>horrifier</quote>
               </cit>
               <cit type="example">
                  <quote>she was horrified at the expense.</quote>
                  <cit type="translation" xml:lang="en">
                     <quote>elle était horrifiée par la dépense.</quote>
                  </cit>
                </cit>
              </entry>
         </div>
      </body>
  </text>
</TEI>
