=== JulietteBenguigui/TEI_XML_French-Breton_dict/MIDTERM_ASSIGNEMENT/dict_dtd.dtd
<?xml encoding="UTF-8"?>

<!-- TEI HEADER -->
<!ELEMENT TEI (teiHeader, text)>
<!ATTLIST TEI xmlns CDATA #IMPLIED>

<!ELEMENT teiHeader (fileDesc, encodingDesc?, profileDesc?)>

<!ELEMENT fileDesc (titleStmt, editionStmt+, publicationStmt, sourceDesc)>
<!ATTLIST filDesc xml:lang CDATA #REQUIRED >

<!ELEMENT titleStmt (title*, author*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA) >

<!ELEMENT editionStmt (edition, respStmt*) >
<!ELEMENT edition (#PCDATA) >
<!ELEMENT respStmt (resp, name) >
<!ELEMENT resp (#PCDATA) >
<!ELEMENT name (#PCDATA) >

<!ELEMENT publicationStmt (distributor?, date?, availability)>
<!ELEMENT distributor (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT availability (licence)>
<!ELEMENT licence (ref?)>
<!ELEMENT ref (#PCDATA)>

<!ELEMENT sourceDesc (p)>
<!ELEMENT p (#PCDATA)>

<!ELEMENT encodingDesc (projectDesc, samplingDecl?) >
<!ATTLIST encodingDesc xml:lang CDATA #REQUIRED >
<!ELEMENT projectDesc (p) >
<!ELEMENT samplingDecl (p) >

<!--  USEFULL TO UNDERSAND THE DIFFERENT LANGUAGES WITHIN THE TEXT -->
<!ELEMENT profileDesc (langUsage, textDesc)>
<!ATTLIST profileDesc xml:lang CDATA #REQUIRED >
<!ELEMENT langUsage (language+)>
<!ELEMENT language (#PCDATA)>
<!ATTLIST language n CDATA #IMPLIED >
<!ATTLIST language ident CDATA #REQUIRED >

<!ELEMENT textDesc (channel?, constitution?, derivation?, domain?, factuality?, interaction?, preparedness?, purpose?)>
<!ATTLIST textDesc n CDATA #IMPLIED>
<!ELEMENT channel (#PCDATA)>
<!ELEMENT constitution (#PCDATA)>
<!ELEMENT derivation (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT factuality (#PCDATA)>
<!ELEMENT interaction (#PCDATA)>
<!ELEMENT preparedness (#PCDATA)>
<!ELEMENT purpose (#PCDATA)>

<!-- TEXT ELEMENT -->
<!ELEMENT text (body+)>
<!ELEMENT body (head?, div+)>
<!ELEMENT head (#PCDATA)>

<!ELEMENT div (head, pb?, fw?, entry+)>
<!ATTLIST div xml:id CDATA #REQUIRED>
<!ELEMENT pb EMPTY>
<!ATTLIST pb n CDATA #REQUIRED >
<!ELEMENT fw (#PCDATA)>

<!ELEMENT entry (form+, sense?, note*)>
<!ATTLIST entry xml:id CDATA #IMPLIED>

<!ELEMENT form (orth+, gramGrp?)>
<!ATTLIST form n CDATA #IMPLIED>
<!ATTLIST form xml:lang CDATA #IMPLIED>

<!ELEMENT orth (#PCDATA)>

<!ELEMENT gramGrp (gen?, pos?, number?)>
<!ELEMENT gen (#PCDATA)>
<!ELEMENT pos (#PCDATA)>
<!ELEMENT number (#PCDATA)>

<!-- STRUCTURE TO HIGHLIGHT DIFFERNET TRANSLATIONS -->
<!ELEMENT sense (cit+)>
<!ELEMENT cit (quote, cit?)>
<!ATTLIST cit type (translation | example) #REQUIRED>
<!ATTLIST cit xml:lang CDATA #IMPLIED>
<!ELEMENT quote (#PCDATA)>

<!ELEMENT note (#PCDATA) >

=== JulietteBenguigui/TEI_XML_French-Breton_dict/MIDTERM_ASSIGNEMENT/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "dict_dtd.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
     <fileDesc>
        <titleStmt>
           <title></title>
        </titleStmt>
        <editionStmt>
           <edition></edition>
           <respStmt>
              <resp></resp>
              <name></name>
           </respStmt>
        </editionStmt>
        <publicationStmt>
           <distributor></distributor>
           <date></date>
           <availability>
              <licence>
                 <ref/>
              </licence>
           </availability>
        </publicationStmt>
        <sourceDesc>
            <p></p>
        </sourceDesc>
     </fileDesc>
     
     <encodingDesc xml:lang="">
        <projectDesc>
           <p></p>
        </projectDesc>
        <samplingDecl>
           <p></p>
        </samplingDecl>
     </encodingDesc>
     
     <profileDesc xml:lang=""> 
        <langUsage>
           <language n="" ident=""></language>
        </langUsage>
        <textDesc n="">
           <channel></channel>
           <constitution/>
           <derivation/>
           <domain/>
           <factuality></factuality>
           <interaction></interaction>
           <preparedness></preparedness>
           <purpose></purpose>
        </textDesc>
     </profileDesc>
 
  </teiHeader>
  
   
   <text>
      <body>
         <head></head>
         <div xml:id="dict_corpus">
            <head></head>
            <pb n=""/>
            <fw></fw>
            <entry xml:id="entry1">
               <form n="">
                  <orth></orth>
                  <gramGrp>
                     <gen></gen>
                     <pos></pos>
                     <number></number>
                  </gramGrp>
               </form>
               <sense>
                  <cit type="example" xml:lang="">
                     <quote></quote>
                  </cit>
                  <cit type="translation" xml:lang="">
                     <quote></quote>
                  </cit>
               </sense>
               <note></note>
            </entry>
         </div>
      </body>
  </text>
</TEI>
